version: "3.8"
services:
  api:
    build: ./api
    container_name: mean_to_do_list
    ports:
      - "4000:4000"
    volumes:
      - ./api:/app
      - /Users/melaniedang/Documents/DVLT/mean-to-do-list/api/node_modules/
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  mongo-express:
    image: mongo-express
    container_name: mongo_express_container
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

volumes:
  mongo_data:
